"""
Django settings for cheerleader project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

ENV_IS_LOCAL = os.environ['ENV'] == 'dev'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = ENV_IS_LOCAL

ALLOWED_HOSTS = [
    '.hirejasperlin.com',
]
if ENV_IS_LOCAL:
    ALLOWED_HOSTS.extend([
        'localhost',
        '127.0.0.1',
    ])

# Application definition
INSTALLED_APPS = [
    'users',
    'chat',
    'meetings',
    'corsheaders',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    'https://www.hirejasperlin.com',
]
CSRF_TRUSTED_ORIGINS = [
    'https://www.hirejasperlin.com',
]
if ENV_IS_LOCAL:
    CORS_ALLOWED_ORIGINS.extend([
        'http://localhost:5173',
        'http://127.0.0.1:5173',
    ])
    CSRF_TRUSTED_ORIGINS.extend([
        'http://localhost:5173',
        'http://127.0.0.1:5173',
    ])

ROOT_URLCONF = 'cheerleader.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cheerleader.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Production security headers
if not ENV_IS_LOCAL:
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    CSRF_COOKIE_DOMAIN = '.hirejasperlin.com'
    CSRF_COOKIE_SECURE = True

# Sessions
SESSION_COOKIE_AGE = 86400  # 1 day
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = not ENV_IS_LOCAL
SESSION_SAVE_EVERY_REQUEST = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MODEL_NAME = os.getenv('MODEL_NAME', 'claude-haiku-4-5-20251001')
PROMPT_FILE_PATH = BASE_DIR / os.getenv('PROMPT_FILE_PATH')
MAX_USER_MESSAGE_CHAR_LENGTH = int(os.getenv('MAX_USER_MESSAGE_CHAR_LENGTH', 800))
MAX_USER_MESSAGE_COUNT = int(os.getenv('MAX_USER_MESSAGE_COUNT', 3))

EMAIL_ADDRESS = os.getenv('EMAIL_ADDRESS')
PHONE_NUMBER = os.getenv('PHONE_NUMBER')
ADMIN_SECRET_KEY = os.getenv('ADMIN_SECRET_KEY')
CALENDLY_API_KEY = os.getenv('CALENDLY_API_KEY')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.mail.me.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('EMAIL_HOST_USER')
